### ISSUE TITLE
add micro-specification to discovery MCFs

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2node#26]
Collection level [MCFs via pygeometa](https://geopython.github.io/pygeometa/reference/mcf/) manage discovery metadata management and publishing to the catalogue.  All data transformations/publications require MCFs to be fed through wis2node.

The MCF format (simply YAML) can be extended as desired without affecting compliance.

Add a `wis2node` extension to MCFs which defines the data's local directory, retention time, etc.

**Comment by tomkralidis** [comment]
```yaml
wis2node:
    retention: P1D
    topic-hierarchy: YYYY-MM-DD.country.data_category.dataset_name  # TBD
```
We will need to bottom out the directory hierarchy as part of #31

**Comment by tomkralidis** [comment]
Updated proposal/example:

```yaml
    retention: P30D
    data_category: observations-surface-land
    country_code: mw
    originating_centre: FWCL
    station_type: landFixed
```
